# Generated by Django 5.1 on 2024-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('Id_pago', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Contraseña', models.CharField(max_length=50)),
                ('Efectivo_o_Tarjeta', models.CharField(max_length=20)),
            ],
        ),
    ]
